#!/usr/bin/python3
import colorsys
import numpy

def get_N_HexCol(N=5):

    HSV_tuples = [(x*1.0/N, 0.5, 0.5) for x in range(N)]
    hex_out = []
    for rgb in HSV_tuples:
        rgb = map(lambda x: int(x*255),colorsys.hsv_to_rgb(*rgb))
        hex_out.append( list(rgb)  )
    return hex_out

all=get_N_HexCol(10)
print( all[0] )
