#!/bin/bash

### allowed AP ###
APSlist=( "jerg_hack"  "drakula5"  )




###########################################
#
#   rekillwpa - ACTION IS HERE
#
###########################################

function rekillwpa(){
    echo ! ... ... killing current AP for new ${1}
    sudo pkill wpa_supplicant
    sleep 3 
    echo ! ... connecting to  ${1}
    WPAFILE="/etc/wpa_supplicant/wpa_${1}.conf"
    echo "   ... while using ${WPAFILE}"
    if [ -e "$WPAFILE" ]; then
        echo "   ... exists:"
        sudo wpa_supplicant -Dnl80211 -iwlan0 -c $WPAFILE >/dev/null &
    else
	echo x... doesnt exist: ${WPAFILE}
    fi	
    sleep 1  
}



function who_am_i(){
    ME=`iwconfig wlan0 | grep ESSID | awk -F\" '{print $2}' `
    echo "$ME"
}


function prefferedAP(){
brk=0

visible=( `sudo iwlist wlan0 scan | grep  ESSID` )

echo "i... ${#visible[*]} ... APs detected" 1>&2


### Now test my AP list
for li in  "${APSlist[@]}"; do
    echo "T " Taking from LIST  /$li/ 1>&2
    o=0
    for vi in "${visible[@]}"; do
	o=$(( $o + 1 ))
	echo "...    " comparing if $vi is on the list:  $li 1>&2
	#echo "    ..." $o AP=$vi  1>&2
	echo "..." $vi | grep -e "$li" >/dev/null
	####################### I HAVE DETECTED A LISTED AP /BEGIN
	if [ "$?" = "0" ]; then
	    echo "... ------" $li is visible AP!  1>&2
	    echo "$li"   #### THIS IS OUTPUT !!!
	    brk=1
	    break
	fi
	####################### I HAVE DETECTED A LISTED AP /END
    done
    if [ "$brk" = "1" ]; then
	echo "... ... breaking 2"  1>&2
	break
    fi
done
}






################################## MAIN #############
for ((i=0;i<1;i++)); do 
clear

iam="$( who_am_i )"
echo "i... I am on $iam"
newAP="$( prefferedAP )"
echo "suggested AP is /${newAP}/"
if [ "$newAP" != "" ]; then
	if [ "$iam" != "$newAP" ]; then
		echo !... going for a new AP ${newAP}
		rekillwpa ${newAP} 
	else
		echo i ... already on ${newAP} ... no action
	fi
else
	echo staying like $iam
fi

sleep 7
### main for
done
