#!/bin/bash

### allowed AP ###
APSlist=( "jerg_hack"  "drakula" "test" "iwselect" )


visible=( `ls -1` )


###########################################
#
#   
#
###########################################

function rekillwpa(){
    echo ! ... seeing jerg_hack ... killing
    sudo pkill wpa_supplicant
    echo W ... connecting to jerg_hack
    # sudo wpa_supplicant -Dnl80211 -iwlan0 -c /etc/wpa_supplicant/wpa_jerg.conf >/dev/null &
    echo searching for /etc/wpa_supplicant/wpa_${1}
    sleep 1  
}



function who_am_i(){
    ME=`iwconfig wlan0 | grep ESSID | awk -F\" '{print $2}' `
    echo "$ME"
}

function prefferedAP(){
o=0
brk=0
for vi in "${visible[@]}"; do
    o=$(( $o + 1 ))
    echo $o AP=$vi  1>&2
    ### Now test my AP list
    for li in  "${APSlist[@]}"; do
	echo "...    " testing $vi for allowed $li 1>&2
	echo "..." $vi | grep -e "$li" >/dev/null
	####################### I HAVE DETECTED A LISTED AP /BEGIN
	if [ "$?" = "0" ]; then
	    echo "... ------" $li is visible AP!  1>&2
	    echo ... $li
	    brk=1
	    break
	fi
	####################### I HAVE DETECTED A LISTED AP /END
    done
    if [ "$brk" = "1" ]; then
	echo ... ... breaking 2  1>&2
	break
    fi
done
}



################################## MAIN #############
iam="$( who_am_i )"
newAP="$( prefferedAP )"
echo "new AP is /$newAP/"
if [ "$newAP" != "" ]; then
    rekillwpa ${newAP} 
fi
